### ISSUE TITLE
Plugin shows no variables

### ISSUE THREAD

**Issue by niklas-may** [mark-nicepants/variables2json-docs#6] opened 2023-07-13 10:14 UTC
I use this plugin in a Figma file, where it used to work before. suddenly it does show no variables anymore
the console throws this error

```
unhandled promise rejection: Error: in get_valuesByMode: invalid variable data values for node
```

any ideas where this is coming from?

**Comment by KushwahRatii** [comment] 2023-07-13 11:24
The error message "unhandled promise rejection: Error: in get_valuesByMode: invalid variable data values for node" suggests that there might be an issue with the variable data values for a specific node in your Figma file. Here are a few steps you can take to troubleshoot and resolve the problem:

1. Check the plugin's compatibility: Make sure that the plugin you're using is compatible with the version of Figma you're currently working on. Plugins occasionally require updates to function correctly with new Figma versions.

2. Confirm variable usage: Verify that the plugin is designed to work with variables and that you have correctly implemented and assigned values to the variables in your Figma file. Double-check if any recent changes have affected the variable values or their usage.

3. Review recent changes: Examine any recent changes you made to your Figma file, such as modifications to styles, components, or variable-related settings. Revert any changes you suspect might have caused the issue and observe if the problem persists.

4. Disable other plugins: Temporarily disable other plugins in your Figma file to check if any conflicts or interference may be causing the error. This step will help identify if there are conflicts between plugins that affect the variable functionality.

5. Reach out to the plugin developer: If the issue persists, it's recommended to contact the plugin developer directly. Provide them with the error message, steps to reproduce the issue, and any relevant details about your Figma file. They will be better equipped to assist you with troubleshooting and resolving the problem.

By following these steps, you can narrow down the cause of the issue and hopefully resolve it. Remember to keep your plugins and Figma version up to date to ensure compatibility and stability.

**Closed as completed** 2023-08-21 06:20 UTC
